// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxjrpfhkgohjvkssznco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4anJwZmhrZ29oanZrc3N6bmNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMjE4NzEsImV4cCI6MjA2Njg5Nzg3MX0.gWnB_jDwN2PDmGiqELxTBLvLym8BG5PCo9_E0b8btX0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});